# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: 
  name: Default # Using the default self-hosted agent pool
  demands:
  - Agent.OS -equals Windows_NT  # Remove this line if your agent is not on Windows

steps:
- checkout: self  # Explicitly add checkout step
  
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
