trigger:
- master

pool: 'Default'

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '1.8'  # Match your pom.xml compiler plugin version
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- task: MavenAuthenticate@0
  inputs:
    artifactsFeeds: 

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'  # Changed to match your pom.xml
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package'  # Changed to build the complete project
    options: '-B -e'  # Added for better error output
